
GET http://localhost:4000/

### 

POST http://localhost:4000/expense
Content-Type: application/json

{
    "name": "Delhi_flight",
    "category" : "Travel" ,
    "amount" : 7634,
    "created_by" : "me"
}
 
######
GET http://localhost:4000/expenses

### 


GET http://localhost:4000/expense/Delhi_flight

### 


PUT http://localhost:4000/expense/64ae59544910a1fa52ed22c6/
Content-Type: application/json

{
    "name" : "Dubai_Flight" ,
    "amount" : 12000
}

###

DELETE http://localhost:4000/expense/64ae57114910a1fa52ed22be/